name = "stars-fortran"
version = "0.1.0"
author = "TioT2"

[dependencies]
# fortran-sdl2 = { git = "https://github.com/interkosmos/fortran-sdl2", rev = "cac974790420ba757c17f88678e66b01500319e7" }
fortran-sdl2 = { path = ".local/fortran-sdl2" }

[features]
debug.flags = "--std=f2023 -funsigned -g -fbacktrace -fsanitize=address -fimplicit-none"
release.flags = "--std=f2023 -funsigned -O3 -DNDEBUG -march=native"

[profiles]
debug = ["debug"]
release = ["release"]

[build]
link = [ "SDL2" ]